# Generated by Django 5.1.6 on 2025-03-09 08:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_round_team_game_bet"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="bet",
            name="odd1",
        ),
        migrations.RemoveField(
            model_name="bet",
            name="odd2",
        ),
        migrations.CreateModel(
            name="Odds",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("odd1", models.FloatField()),
                ("odd2", models.FloatField()),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("modified", models.DateTimeField(auto_now=True)),
                (
                    "round",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="api.round"
                    ),
                ),
                (
                    "team",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="api.team"
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="bet",
            name="odds",
            field=models.ForeignKey(
                default=0,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="bets",
                to="api.odds",
            ),
            preserve_default=False,
        ),
    ]
