# Generated by Django 5.1.6 on 2025-03-12 14:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0004_bonus"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="footballclub",
            name="characteristic",
        ),
        migrations.RemoveField(
            model_name="footballclub",
            name="country",
        ),
        migrations.RemoveField(
            model_name="footballclub",
            name="league",
        ),
        migrations.DeleteModel(
            name="Characteristic",
        ),
        migrations.DeleteModel(
            name="Country",
        ),
        migrations.DeleteModel(
            name="FootballClub",
        ),
        migrations.DeleteModel(
            name="League",
        ),
    ]
